# Generated by Django 6.0 on 2025-12-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_tbl_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_users',
            name='user_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
