# Generated by Django 6.0 on 2025-12-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_tbl_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roles_name', models.CharField(max_length=50)),
            ],
        ),
    ]
