# Generated by Django 6.0 on 2025-12-29 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_tbl_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_companyregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Companyname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('CompanyLogo', models.FileField(upload_to='Assets/Company/')),
                ('Registeredaddress', models.CharField(max_length=50)),
                ('DateofIncorporation', models.DateField()),
                ('uploaddocuments', models.FileField(upload_to='Assets/Document/')),
                ('industry', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_documenttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documenttype_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='tbl_users',
            name='place',
        ),
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_date', models.DateField()),
                ('complaint_status', models.CharField(max_length=200)),
                ('complaint_description', models.CharField(max_length=500)),
                ('reply', models.CharField(max_length=50)),
                ('adminid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_admin')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_users')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to='Assets/Document/')),
                ('document_date', models.DateField()),
                ('document_status', models.CharField(max_length=200)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_users')),
                ('documenttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_documenttype')),
            ],
        ),
    ]
