# Generated by Django 6.0 on 2025-12-29 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_tbl_companyregistration_tbl_documenttype_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_companyregistration',
        ),
    ]
