# Generated by Django 6.0 on 2025-12-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_tbl_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_company',
        ),
    ]
