# Generated by Django 6.0 on 2025-12-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_delete_tbl_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_email', models.EmailField(max_length=254, unique=True)),
                ('company_contact', models.CharField(max_length=50)),
                ('company_address', models.CharField(max_length=50)),
                ('company_password', models.CharField(max_length=50)),
                ('company_license', models.FileField(upload_to='Assets/Company/')),
                ('company_logo', models.FileField(upload_to='Assets/Company/')),
            ],
        ),
    ]
