# Generated by Django 6.0 on 2026-01-02 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_tbl_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_company',
            name='company_logo',
        ),
        migrations.DeleteModel(
            name='tbl_subcategory',
        ),
    ]
