# Generated by Django 6.0 on 2026-01-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_remove_tbl_company_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_category',
            name='category_name',
            field=models.CharField(max_length=100),
        ),
    ]
