# Generated by Django 6.0 on 2026-01-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_alter_tbl_category_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_stockprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateField()),
                ('stock_price', models.FloatField()),
                ('stockvolume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tbl_wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField()),
                ('walletbalance', models.DateField()),
            ],
        ),
    ]
