# Generated by Django 6.0 on 2026-01-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_tbl_stockprice_tbl_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_wallet',
            name='userid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_wallet',
            name='walletbalance',
            field=models.DateField(max_length=50),
        ),
    ]
