# Generated by Django 6.0 on 2026-01-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_alter_tbl_wallet_userid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='adminid',
        ),
        migrations.DeleteModel(
            name='tbl_category',
        ),
        migrations.DeleteModel(
            name='tbl_company',
        ),
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='tbl_place',
            name='district',
        ),
        migrations.RemoveField(
            model_name='tbl_document',
            name='documenttype',
        ),
        migrations.RemoveField(
            model_name='tbl_document',
            name='userid',
        ),
        migrations.DeleteModel(
            name='tbl_Roles',
        ),
        migrations.DeleteModel(
            name='tbl_stockprice',
        ),
        migrations.DeleteModel(
            name='tbl_wallet',
        ),
        migrations.DeleteModel(
            name='tbl_admin',
        ),
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
        migrations.DeleteModel(
            name='tbl_district',
        ),
        migrations.DeleteModel(
            name='tbl_place',
        ),
        migrations.DeleteModel(
            name='tbl_documenttype',
        ),
        migrations.DeleteModel(
            name='tbl_document',
        ),
        migrations.DeleteModel(
            name='tbl_users',
        ),
    ]
