# Generated by Django 6.0 on 2026-01-06 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0018_remove_tbl_complaint_adminid_delete_tbl_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=50)),
                ('admin_password', models.CharField(max_length=50)),
                ('admin_email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_email', models.EmailField(max_length=254, unique=True)),
                ('company_contact', models.CharField(max_length=50)),
                ('company_address', models.CharField(max_length=50)),
                ('company_password', models.CharField(max_length=50)),
                ('company_license', models.FileField(upload_to='Assets/Company/')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_district',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_documenttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documenttype_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roles_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_stockprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateField()),
                ('stock_price', models.FloatField()),
                ('stockvolume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tbl_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_contact', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_photo', models.FileField(upload_to='Assets/User/')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=50)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_district')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to='Assets/Document/')),
                ('document_date', models.DateField()),
                ('document_status', models.CharField(max_length=200)),
                ('documenttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_documenttype')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_users')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_date', models.DateField()),
                ('complaint_status', models.CharField(max_length=200)),
                ('complaint_description', models.CharField(max_length=500)),
                ('reply', models.CharField(max_length=50)),
                ('adminid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_admin')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_users')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walletbalance', models.DateField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_users')),
            ],
        ),
    ]
