# Generated by Django 6.0 on 2026-01-06 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_document',
            name='documenttype',
        ),
        migrations.RemoveField(
            model_name='tbl_document',
            name='userid',
        ),
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
        migrations.DeleteModel(
            name='tbl_document',
        ),
    ]
