# Generated by Django 6.0 on 2026-01-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_remove_tbl_document_documenttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_stockprice',
            name='stock_price',
            field=models.IntegerField(),
        ),
    ]
