# Generated by Django 6.0 on 2026-01-07 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0021_alter_tbl_stockprice_stock_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_wallet',
            name='walletbalance',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='tbl_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.FileField(upload_to='Assets/stock')),
                ('stock_status', models.CharField(max_length=100)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_category')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_company')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=100)),
                ('order_quantity', models.IntegerField()),
                ('order_price', models.IntegerField()),
                ('order_status', models.CharField(max_length=100)),
                ('order_datetime', models.DateTimeField()),
                ('order_usersid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_users')),
                ('order_stockid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_stock')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_exicuteprice', models.CharField(max_length=100)),
                ('trade_quantity', models.IntegerField()),
                ('trade_datetime', models.DateTimeField()),
                ('trade_orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_order')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_wallettransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallettransaction_type', models.CharField(max_length=100)),
                ('wallettransaction_amount', models.CharField(max_length=100)),
                ('wallettransaction_timedate', models.DateTimeField(max_length=100)),
                ('wallettransaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_wallet')),
                ('wallettransaction_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_order')),
            ],
        ),
    ]
