# Generated by Django 6.0 on 2026-01-12 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0022_alter_tbl_wallet_walletbalance_tbl_stock_tbl_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_wallettransaction',
            name='wallettransaction_order',
        ),
        migrations.RemoveField(
            model_name='tbl_trade',
            name='trade_orderid',
        ),
        migrations.RemoveField(
            model_name='tbl_wallet',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tbl_wallettransaction',
            name='wallettransaction_id',
        ),
        migrations.DeleteModel(
            name='tbl_order',
        ),
        migrations.DeleteModel(
            name='tbl_trade',
        ),
        migrations.DeleteModel(
            name='tbl_users',
        ),
        migrations.DeleteModel(
            name='tbl_wallet',
        ),
        migrations.DeleteModel(
            name='tbl_wallettransaction',
        ),
    ]
