# Generated by Django 6.0 on 2026-01-12 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0023_remove_tbl_wallettransaction_wallettransaction_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=50)),
                ('user_contact', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_photo', models.FileField(upload_to='Assets/User/')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=100)),
                ('order_quantity', models.IntegerField()),
                ('order_price', models.IntegerField()),
                ('order_status', models.CharField(max_length=100)),
                ('order_datetime', models.DateTimeField()),
                ('order_stockid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_stock')),
                ('order_usersid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_users')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_exicuteprice', models.CharField(max_length=100)),
                ('trade_quantity', models.IntegerField()),
                ('trade_datetime', models.DateTimeField()),
                ('trade_orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_order')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walletbalance', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_users')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_wallettransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallettransaction_type', models.CharField(max_length=100)),
                ('wallettransaction_amount', models.CharField(max_length=100)),
                ('wallettransaction_timedate', models.DateTimeField(max_length=100)),
                ('wallettransaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_wallet')),
                ('wallettransaction_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_order')),
            ],
        ),
    ]
