# Generated by Django 6.0.1 on 2026-02-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0024_tbl_users_tbl_order_tbl_trade_tbl_wallet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_stock',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='tbl_order',
            name='order_stockid',
        ),
        migrations.RemoveField(
            model_name='tbl_order',
            name='order_usersid',
        ),
        migrations.RemoveField(
            model_name='tbl_wallettransaction',
            name='wallettransaction_order',
        ),
        migrations.RemoveField(
            model_name='tbl_trade',
            name='trade_orderid',
        ),
        migrations.RemoveField(
            model_name='tbl_stock',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='tbl_wallettransaction',
            name='wallettransaction_id',
        ),
        migrations.DeleteModel(
            name='tbl_company',
        ),
        migrations.DeleteModel(
            name='tbl_order',
        ),
        migrations.DeleteModel(
            name='tbl_trade',
        ),
        migrations.DeleteModel(
            name='tbl_stock',
        ),
        migrations.DeleteModel(
            name='tbl_wallettransaction',
        ),
    ]
