# Generated by Django 6.0.1 on 2026-02-03 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0025_remove_tbl_stock_company_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_details', models.CharField(max_length=50)),
                ('company_proof', models.FileField(upload_to='Assets/Company/')),
                ('company_photo', models.FileField(max_length=50, null=True, upload_to='')),
                ('company_status', models.CharField(max_length=50)),
                ('company_license', models.FileField(upload_to='Assets/Company/')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.FileField(upload_to='Assets/stock')),
                ('stock_status', models.CharField(max_length=100)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_category')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_company')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=100)),
                ('order_quantity', models.IntegerField()),
                ('order_price', models.IntegerField()),
                ('order_status', models.CharField(max_length=100)),
                ('order_datetime', models.DateTimeField()),
                ('order_usersid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_users')),
                ('order_stockid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_stock')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_exicuteprice', models.CharField(max_length=100)),
                ('trade_quantity', models.IntegerField()),
                ('trade_datetime', models.DateTimeField()),
                ('trade_orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_order')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_wallettransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallettransaction_type', models.CharField(max_length=100)),
                ('wallettransaction_amount', models.CharField(max_length=100)),
                ('wallettransaction_timedate', models.DateTimeField(max_length=100)),
                ('wallettransaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_wallet')),
                ('wallettransaction_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_order')),
            ],
        ),
    ]
