# Generated by Django 6.0.3 on 2026-03-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0026_tbl_company_tbl_stock_tbl_order_tbl_trade_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_admin',
        ),
        migrations.RemoveField(
            model_name='tbl_stock',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='tbl_stock',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='tbl_place',
            name='district',
        ),
        migrations.DeleteModel(
            name='tbl_documenttype',
        ),
        migrations.RemoveField(
            model_name='tbl_order',
            name='order_stockid',
        ),
        migrations.RemoveField(
            model_name='tbl_order',
            name='order_usersid',
        ),
        migrations.RemoveField(
            model_name='tbl_trade',
            name='trade_orderid',
        ),
        migrations.RemoveField(
            model_name='tbl_wallettransaction',
            name='wallettransaction_order',
        ),
        migrations.DeleteModel(
            name='tbl_Roles',
        ),
        migrations.DeleteModel(
            name='tbl_stockprice',
        ),
        migrations.RemoveField(
            model_name='tbl_wallet',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tbl_wallettransaction',
            name='wallettransaction_id',
        ),
        migrations.DeleteModel(
            name='tbl_category',
        ),
        migrations.DeleteModel(
            name='tbl_company',
        ),
        migrations.DeleteModel(
            name='tbl_district',
        ),
        migrations.DeleteModel(
            name='tbl_place',
        ),
        migrations.DeleteModel(
            name='tbl_stock',
        ),
        migrations.DeleteModel(
            name='tbl_trade',
        ),
        migrations.DeleteModel(
            name='tbl_order',
        ),
        migrations.DeleteModel(
            name='tbl_users',
        ),
        migrations.DeleteModel(
            name='tbl_wallet',
        ),
        migrations.DeleteModel(
            name='tbl_wallettransaction',
        ),
    ]
