# Generated by Django 6.0.3 on 2026-03-05 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0027_delete_tbl_admin_remove_tbl_stock_category_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=50)),
                ('admin_password', models.CharField(max_length=50)),
                ('admin_email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_details', models.CharField(max_length=200)),
                ('company_proof', models.FileField(upload_to='assets/company/')),
                ('company_photo', models.FileField(null=True, upload_to='assets/company/')),
                ('company_license', models.FileField(upload_to='assets/company/')),
                ('company_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_district',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_documenttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documenttype_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_stockprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateField()),
                ('stock_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tbl_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=50)),
                ('user_contact', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=200)),
                ('user_password', models.CharField(max_length=50)),
                ('user_photo', models.FileField(upload_to='assets/user/')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=50)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_district')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=20)),
                ('stock_status', models.IntegerField(default=1)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_category')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_company')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=50)),
                ('order_quantity', models.IntegerField()),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_status', models.IntegerField(default=0)),
                ('order_datetime', models.DateTimeField(auto_now_add=True)),
                ('order_stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_stock')),
                ('order_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_users')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_executeprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trade_quantity', models.IntegerField()),
                ('trade_datetime', models.DateTimeField(auto_now_add=True)),
                ('trade_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_order')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_users')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_wallettransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallettransaction_type', models.CharField(max_length=50)),
                ('wallettransaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wallettransaction_timedate', models.DateTimeField(auto_now_add=True)),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_wallet')),
                ('wallettransaction_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_order')),
            ],
        ),
    ]
