# Generated by Django 6.0.3 on 2026-03-05 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0028_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_admin',
        ),
        migrations.RemoveField(
            model_name='tbl_stock',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='tbl_stock',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='tbl_place',
            name='district_id',
        ),
        migrations.DeleteModel(
            name='tbl_documenttype',
        ),
        migrations.RemoveField(
            model_name='tbl_order',
            name='order_stock_id',
        ),
        migrations.RemoveField(
            model_name='tbl_order',
            name='order_user_id',
        ),
        migrations.RemoveField(
            model_name='tbl_wallettransaction',
            name='wallettransaction_order_id',
        ),
        migrations.RemoveField(
            model_name='tbl_trade',
            name='trade_order_id',
        ),
        migrations.DeleteModel(
            name='tbl_roles',
        ),
        migrations.DeleteModel(
            name='tbl_stockprice',
        ),
        migrations.RemoveField(
            model_name='tbl_wallet',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tbl_wallettransaction',
            name='wallet_id',
        ),
        migrations.DeleteModel(
            name='tbl_category',
        ),
        migrations.DeleteModel(
            name='tbl_company',
        ),
        migrations.DeleteModel(
            name='tbl_district',
        ),
        migrations.DeleteModel(
            name='tbl_place',
        ),
        migrations.DeleteModel(
            name='tbl_stock',
        ),
        migrations.DeleteModel(
            name='tbl_order',
        ),
        migrations.DeleteModel(
            name='tbl_trade',
        ),
        migrations.DeleteModel(
            name='tbl_users',
        ),
        migrations.DeleteModel(
            name='tbl_wallet',
        ),
        migrations.DeleteModel(
            name='tbl_wallettransaction',
        ),
    ]
