# Generated by Django 6.0.3 on 2026-03-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0030_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_company',
            name='company_email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
