# Generated by Django 6.0.3 on 2026-03-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0031_tbl_company_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_company',
            name='company_password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
